/**
 * 👑 AYABUS PARTNER PORTAL (Sovereign Store Engine)
 * ------------------------------------------------------------------
 * Module: Partner Store / Vaults
 * File: CorporateIdentity.jsx
 * * DESCRIPTION:
 * The Master Dashboard for the Partner's core operational profile. 
 * Renders the exact payload generated by the Admin Cockpit's onboarding 
 * wizard (Credentials, Parks, Financials, Contacts).
 * * WORLD-CLASS PHYSICS:
 * 1. MASONRY ARCHITECTURE: Uses CSS Grid to perfectly balance the 4 data 
 * pillars across any screen size (Desktop to Mobile).
 * 2. DATA MASKING: Automatically masks sensitive bank account numbers 
 * (•••• 1234) for over-the-shoulder security in a busy dispatch office.
 * 3. KINETIC MODIFICATION TRIGGERS: Each card features a contextual 
 * "Request Change" button that wires directly into the ChangeRequestEngine.
 * 4. EMPTY STATE GRACE: Defensively renders empty arrays if a legacy 
 * partner record is missing contacts or parks.
 */

import React from 'react';
import { 
    Building2, MapPin, Wallet, Users, 
    ShieldCheck, Calendar, Phone, Mail, 
    Navigation, CreditCard, Star, FileEdit, AlertTriangle
} from 'lucide-react';
import StoreAssetBadge from '../interactive/StoreAssetBadge';

// ========================================================================
// SECURITY HELPER
// ========================================================================
const maskAccountNumber = (accNumber) => {
    if (!accNumber || accNumber.length < 4) return '•••• ••••';
    const last4 = accNumber.slice(-4);
    return `•••• •••• ${last4}`;
};

// ========================================================================
// MAIN COMPONENT
// ========================================================================
const CorporateIdentity = ({ profile, onRequestChange }) => {

    if (!profile) {
        return (
            <div className="vault-empty-state">
                <AlertTriangle size={32} color="var(--status-error)" />
                <h3>Profile Sync Failure</h3>
                <p>The Sovereign Engine could not retrieve your corporate identity.</p>
            </div>
        );
    }

    return (
        <div className="corporate-vault-chassis">
            
            {/* --- MASTER HEADER --- */}
            <header className="vault-header">
                <div className="header-identity">
                    <div className="company-avatar">
                        <Building2 size={24} color="#fff" />
                    </div>
                    <div className="company-titles">
                        <h1>{profile.companyName}</h1>
                        <div className="company-meta">
                            <span className="partner-id">ID: {profile.partnerId}</span>
                            <StoreAssetBadge status={profile.status} size="sm" />
                        </div>
                    </div>
                </div>
            </header>

            {/* --- MASONRY GRID --- */}
            <div className="vault-grid">

                {/* ==========================================
                    CARD 1: CREDENTIALS & IDENTITY
                ========================================== */}
                <div className="vault-card">
                    <div className="card-header">
                        <div className="card-title">
                            <ShieldCheck size={18} color="var(--brand-primary)" />
                            <h3>Legal Identity</h3>
                        </div>
                    </div>
                    <div className="card-body">
                        <div className="data-row">
                            <span className="data-label">Tax ID (TIN)</span>
                            <span className="data-value highlight">{profile.tinNumber || 'PENDING'}</span>
                        </div>
                        <div className="data-row">
                            <span className="data-label">Business Type</span>
                            <span className="data-value">{profile.businessType || 'N/A'}</span>
                        </div>
                        <div className="data-row">
                            <span className="data-label">Incorporation Date</span>
                            <span className="data-value">
                                {profile.incorporationDate ? new Date(profile.incorporationDate).toLocaleDateString() : 'N/A'}
                            </span>
                        </div>
                    </div>
                </div>

                {/* ==========================================
                    CARD 2: OPERATIONAL PARKS
                ========================================== */}
                <div className="vault-card">
                    <div className="card-header">
                        <div className="card-title">
                            <MapPin size={18} color="var(--brand-primary)" />
                            <h3>Approved Stages & Parks</h3>
                        </div>
                        <button 
                            className="change-trigger-btn"
                            onClick={() => onRequestChange('PERSONNEL_CHANGE')} // Contextual trigger
                            title="Request Park Update"
                        >
                            <FileEdit size={14} />
                        </button>
                    </div>
                    <div className="card-body scrollable-list">
                        {profile.parks && profile.parks.length > 0 ? (
                            profile.parks.map((park, idx) => (
                                <div key={idx} className="list-item">
                                    <div className="item-icon"><Navigation size={14} /></div>
                                    <div className="item-content">
                                        <div className="item-primary">{park.name || 'Unnamed Park'}</div>
                                        <div className="item-secondary">{park.address || 'Address not listed'}</div>
                                        {park.gps_lat && (
                                            <div className="item-tertiary">GPS: {park.gps_lat}, {park.gps_lng}</div>
                                        )}
                                    </div>
                                </div>
                            ))
                        ) : (
                            <div className="empty-list">No stages registered.</div>
                        )}
                    </div>
                </div>

                {/* ==========================================
                    CARD 3: FINANCIAL SETTLEMENT
                ========================================== */}
                <div className="vault-card">
                    <div className="card-header">
                        <div className="card-title">
                            <Wallet size={18} color="var(--brand-primary)" />
                            <h3>Treasury Routing</h3>
                        </div>
                        <button 
                            className="change-trigger-btn"
                            onClick={() => onRequestChange('FINANCIAL_UPDATE')}
                        >
                            <FileEdit size={14} />
                        </button>
                    </div>
                    <div className="card-body scrollable-list">
                        {profile.financials && profile.financials.length > 0 ? (
                            profile.financials.map((fin, idx) => (
                                <div key={idx} className={`list-item ${fin.is_primary ? 'is-primary' : ''}`}>
                                    <div className="item-icon"><CreditCard size={14} /></div>
                                    <div className="item-content">
                                        <div className="item-primary">
                                            {fin.institution_code || fin.institutionCode || 'Bank'}
                                            {fin.is_primary && <Star size={12} className="primary-star" />}
                                        </div>
                                        <div className="item-secondary">{fin.account_name || fin.accountName}</div>
                                        <div className="item-tertiary security-mask">
                                            {maskAccountNumber(fin.account_number || fin.accountNumber)}
                                        </div>
                                    </div>
                                </div>
                            ))
                        ) : (
                            <div className="empty-list">No financial routes configured.</div>
                        )}
                    </div>
                </div>

                {/* ==========================================
                    CARD 4: KEY PERSONNEL
                ========================================== */}
                <div className="vault-card">
                    <div className="card-header">
                        <div className="card-title">
                            <Users size={18} color="var(--brand-primary)" />
                            <h3>Authorized Contacts</h3>
                        </div>
                        <button 
                            className="change-trigger-btn"
                            onClick={() => onRequestChange('PERSONNEL_CHANGE')}
                        >
                            <FileEdit size={14} />
                        </button>
                    </div>
                    <div className="card-body scrollable-list">
                        {profile.contacts && profile.contacts.length > 0 ? (
                            profile.contacts.map((contact, idx) => (
                                <div key={idx} className="list-item">
                                    <div className="item-icon"><Phone size={14} /></div>
                                    <div className="item-content">
                                        <div className="item-primary">{contact.fullName || contact.full_name}</div>
                                        <div className="item-secondary role-badge">{contact.role}</div>
                                        <div className="item-tertiary">{contact.phonePrimary || contact.phone_primary}</div>
                                    </div>
                                </div>
                            ))
                        ) : (
                            <div className="empty-list">No contacts registered.</div>
                        )}
                    </div>
                </div>

            </div>

            {/* --- COMPONENT CSS PHYSICS --- */}
            <style>{`
                .corporate-vault-chassis {
                    padding: 32px;
                    max-width: 1400px;
                    margin: 0 auto;
                    animation: fadeIn 0.4s ease;
                }

                /* HEADER PHYSICS */
                .vault-header {
                    margin-bottom: 32px;
                    padding-bottom: 24px;
                    border-bottom: 1px solid var(--border-subtle);
                }
                .header-identity {
                    display: flex;
                    align-items: center;
                    gap: 20px;
                }
                .company-avatar {
                    width: 64px;
                    height: 64px;
                    background: var(--brand-primary);
                    border-radius: 16px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    box-shadow: 0 8px 24px rgba(206, 172, 92, 0.2);
                }
                .company-titles h1 {
                    margin: 0 0 8px 0;
                    font-size: 28px;
                    font-weight: 900;
                    color: var(--text-main);
                    letter-spacing: -0.5px;
                }
                .company-meta {
                    display: flex;
                    align-items: center;
                    gap: 16px;
                }
                .partner-id {
                    font-size: 13px;
                    font-weight: 800;
                    color: var(--text-muted);
                    font-family: monospace;
                    background: var(--bg-input);
                    padding: 4px 10px;
                    border-radius: 6px;
                }

                /* GRID PHYSICS */
                .vault-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(380px, 1fr));
                    gap: 24px;
                }

                /* CARD PHYSICS */
                .vault-card {
                    background: var(--bg-surface);
                    border: 1px solid var(--border-subtle);
                    border-radius: var(--radius-lg);
                    display: flex;
                    flex-direction: column;
                    overflow: hidden;
                    box-shadow: 0 4px 20px rgba(0,0,0,0.02);
                    transition: all 0.3s ease;
                }
                .vault-card:hover {
                    border-color: var(--border-strong);
                    box-shadow: 0 8px 30px rgba(0,0,0,0.04);
                }

                .card-header {
                    padding: 20px 24px;
                    border-bottom: 1px solid var(--border-subtle);
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    background: var(--bg-canvas);
                }
                .card-title {
                    display: flex;
                    align-items: center;
                    gap: 10px;
                }
                .card-title h3 {
                    margin: 0;
                    font-size: 14px;
                    font-weight: 900;
                    color: var(--text-main);
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }

                .change-trigger-btn {
                    background: transparent;
                    border: 1px solid transparent;
                    color: var(--text-muted);
                    width: 32px;
                    height: 32px;
                    border-radius: 8px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    cursor: pointer;
                    transition: all 0.2s;
                }
                .change-trigger-btn:hover {
                    background: rgba(206, 172, 92, 0.1);
                    color: var(--brand-primary);
                    border-color: rgba(206, 172, 92, 0.2);
                }

                .card-body {
                    padding: 24px;
                    flex: 1;
                    display: flex;
                    flex-direction: column;
                    gap: 16px;
                }
                .scrollable-list {
                    max-height: 300px;
                    overflow-y: auto;
                    gap: 12px;
                }
                .scrollable-list::-webkit-scrollbar { width: 4px; }
                .scrollable-list::-webkit-scrollbar-thumb { background: var(--border-strong); border-radius: 4px; }

                /* DATA ROWS (For Credentials) */
                .data-row {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    padding-bottom: 12px;
                    border-bottom: 1px dashed var(--border-subtle);
                }
                .data-row:last-child { border-bottom: none; padding-bottom: 0; }
                .data-label { font-size: 13px; font-weight: 700; color: var(--text-muted); }
                .data-value { font-size: 14px; font-weight: 900; color: var(--text-main); text-align: right; }
                .data-value.highlight { color: var(--brand-primary); font-family: monospace; letter-spacing: 1px; }

                /* LIST ITEMS (Parks, Financials, Contacts) */
                .list-item {
                    display: flex;
                    gap: 16px;
                    padding: 16px;
                    background: var(--bg-input);
                    border: 1px solid var(--border-subtle);
                    border-radius: 12px;
                    transition: all 0.2s;
                }
                .list-item:hover { border-color: var(--border-strong); background: var(--bg-surface); }
                .list-item.is-primary { border-color: var(--brand-primary); background: rgba(206, 172, 92, 0.02); }
                
                .item-icon {
                    width: 32px;
                    height: 32px;
                    background: var(--bg-surface);
                    border: 1px solid var(--border-subtle);
                    border-radius: 8px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    color: var(--text-muted);
                    flex-shrink: 0;
                }
                .list-item.is-primary .item-icon { color: var(--brand-primary); border-color: rgba(206, 172, 92, 0.3); }

                .item-content { display: flex; flex-direction: column; gap: 4px; flex: 1; }
                .item-primary { font-size: 14px; font-weight: 900; color: var(--text-main); display: flex; align-items: center; gap: 8px; }
                .primary-star { color: var(--brand-primary); fill: var(--brand-primary); }
                .item-secondary { font-size: 12px; font-weight: 600; color: var(--text-muted); line-height: 1.4; }
                .item-tertiary { font-size: 11px; font-weight: 700; color: var(--brand-primary); font-family: monospace; margin-top: 4px; }
                
                .role-badge { display: inline-block; padding: 2px 8px; background: rgba(0,0,0,0.05); border-radius: 4px; margin-top: 2px; width: max-content; }
                .security-mask { letter-spacing: 2px; }

                .empty-list {
                    padding: 32px;
                    text-align: center;
                    color: var(--text-muted);
                    font-size: 13px;
                    font-weight: 700;
                    background: var(--bg-input);
                    border-radius: 12px;
                    border: 1px dashed var(--border-strong);
                }

                @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }

                /* MOBILE RESPONSIVE DEGRADATION */
                @media (max-width: 768px) {
                    .corporate-vault-chassis { padding: 16px; }
                    .vault-grid { grid-template-columns: 1fr; }
                    .header-identity { flex-direction: column; align-items: flex-start; text-align: left; }
                    .company-titles h1 { font-size: 24px; }
                }
            `}</style>
        </div>
    );
};

export default CorporateIdentity;